name: Install llvm-msvc
description: Install llvm-msvc

inputs:
  version:
    description: Version to install
    required: false
    default: latest
  path:
    description: Path to store installer
    required: false
    default: $env:TEMP
  token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
    
runs:
  using: composite
  steps:
    - name: Run as admin
      run: |
        $psCommand = 'Start-Process ' + "`"${env:GITHUB_ACTION}`"" + ' -Verb RunAs'
        Start-Process powershell -Verb RunAs -ArgumentList 'Invoke-Expression', $psCommand
        Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
      shell: powershell

    - name: Get the latest release of llvm-msvc
      id: llvm-msvc-latest_release
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.token }}
        script: |
          const { data } = await github.request('GET /repos/{owner}/{repo}/releases/latest', {
            owner: 'backengineering',
            repo: 'llvm-msvc'
          })
          console.log(data.tag_name)
          return data.tag_name
  
    - name: Download and Install llvm-msvc_X86_64_installer.exe
      run: |
        Write-Host "Checking if llvm-msvc_X86_64_installer.exe already exists."
        $releaseVersion = "${{ inputs.version }}"
        Write-Host "Version: $releaseVersion"
        if ($releaseVersion -eq "latest") {
          Write-Host "Use the latest version."
          $releaseVersion = ${{ steps.llvm-msvc-latest_release.outputs.result }}
        }
        $releaseFolder = "${{ inputs.path }}\$releaseVersion"
        Write-Host "Release folder: $releaseFolder"
        if (!(Test-Path -Path $releaseFolder)) {
          New-Item -ItemType Directory -Force -Path $releaseFolder
        }
        $exe = Join-Path $releaseFolder 'llvm-msvc_X86_64_installer.exe'
        Write-Host "exe: $exe"
        
        if (!(Test-Path -Path $exe)) {
          Write-Host "Downloading llvm-msvc_X86_64_installer.exe..."
          $owner = "backengineering"
          $repo = "llvm-msvc"
          $tag = $releaseVersion
          $file = "llvm-msvc_X86_64_installer.exe"
          $credentials="${{ inputs.token }}"
          $releasesUrl = "https://api.github.com/repos/$owner/$repo/releases/tags/$tag"
          $headers = @{
              "Accept" = "application/vnd.github.v3+json"
              "Authorization" = "token $credentials"
          }
          $releases = Invoke-WebRequest -Uri $releasesUrl -Headers $headers | ConvertFrom-Json
          $assetId = ($releases.assets | Where-Object { $_.name -eq $file }).id
          Write-Host "Asset ID: $assetId"
          $url = "https://" + $credentials + ":@api.github.com/repos/$owner/$repo/releases/assets/$assetId"
          $headers2 = @{
              "Accept" = "application/octet-stream"
              "Authorization" = "token $credentials"
          }
          Invoke-WebRequest -Uri $url -Headers $headers2 -OutFile $exe
        } else {
          Write-Host "llvm-msvc_X86_64_installer.exe already exists."
        }

        Write-Host "Installing llvm-msvc_X86_64_installer.exe..."
        Start-Process -Wait -FilePath $exe -ArgumentList '/verysilent' -Verb RunAs
        Write-Host "llvm-msvc_X86_64_installer.exe installed successfully."
      shell: powershell
      
