
name: Install llvm-msvc
description: Install llvm-msvc

inputs:
  version:
    description: Version to install
    required: false
    default: latest
  path:
    description: Path to store installer
    required: false
    default: $env:TEMP
    
runs:
  using: composite
  steps:
    - name: Run as admin
      run: |
        $psCommand = 'Start-Process ' + "`"${env:GITHUB_ACTION}`"" + ' -Verb RunAs'
        Start-Process powershell -Verb RunAs -ArgumentList 'Invoke-Expression', $psCommand
      shell: powershell

    - name: Get the latest release of llvm-msvc
      id: llvm-msvc-latest_release
      uses: actions/github-script@v4
      with:
        script: |
          const { data } = await github.repos.getLatestRelease({
            owner: 'backengineering',
            repo: 'llvm-msvc'
          })
          console.log(data.tag_name)
          return data.tag_name
      
    - name: Download and Install llvm-msvc_X86_64_installer.exe
      run: |
        Write-Host "Checking if llvm-msvc_X86_64_installer.exe already exists."
        $releaseVersion = "${{ inputs.version }}"
        Write-Host "Version: $releaseVersion"
        if ($releaseVersion -eq "latest") {
          Write-Host "Use the latest version."
          $releaseVersion = ${{ steps.llvm-msvc-latest_release.outputs.result }}
        }
        $releaseFolder = "${{ inputs.path }}\$releaseVersion"
        Write-Host "Release folder: $releaseFolder"
        if (!(Test-Path -Path $releaseFolder)) {
          New-Item -ItemType Directory -Force -Path $releaseFolder
        }
        $exe = Join-Path $releaseFolder 'llvm-msvc_X86_64_installer.exe'
        Write-Host "exe: $exe"
        
        if (!(Test-Path -Path $exe)) {
          Write-Host "Downloading llvm-msvc_X86_64_installer.exe..."
          $url = 'https://github.com/backengineering/llvm-msvc/releases/download/' + $releaseVersion + '/llvm-msvc_X86_64_installer.exe'
          Invoke-WebRequest -Uri $url -OutFile $exe
          Write-Host "llvm-msvc_X86_64_installer.exe downloaded successfully."
        } else {
          Write-Host "llvm-msvc_X86_64_installer.exe already exists."
        }

        Write-Host "Installing llvm-msvc_X86_64_installer.exe..."
        Start-Process -Wait -FilePath $exe -ArgumentList '/verysilent' -Verb RunAs
        Write-Host "llvm-msvc_X86_64_installer.exe installed successfully."
      shell: powershell
      

